### ISSUE TITLE
Widget does not always display application name (partial window title instead)

### ISSUE THREAD

**Issue by Chromace** [kupiqu/plasma-active-application#4]
Sometimes, when in use with specific applications, part of the window title will be used rather than the name of the application itself. This can be demonstrated with an example, attached below.

![screenshot_20181107_012622](https://user-images.githubusercontent.com/16624211/48070517-23b06000-e22c-11e8-8446-9499c73c72b6.png)

The expected outcome would be to have the actual application name shown, rather than part of the window title. This can cause further complications with applications which do not have their name inside of them at all, such as Pidgin's conversation windows (they instead show the title of the current conversation currently active).

**Comment by kupiqu** [comment]
Yes, that's correct. Current implementation of the applet derives the application name from the window title. In my experience this has been working better (small letters plus some application names looking bad, as for instance telegramdesktop).

It's not at all difficult to fix the appearance of QMPlay2, by setting a new replacement (see issue #1). I think this should work: `"QMPlay2 - .*", "QMPlay2";`. So in that regard, I'm going to close this issue as won't fix as that is what replacements are specifically for.

But said that, I see that this trick will fail completely on applications that do not show the application name at all... I'll try to think the best way to consider such an issue. I probably need to start using original application names and modify those to make them look better.

Could you please open a new issue for that specific issue? Thanks!

**Comment by Chromace** [comment]
There we go! I do believe the Active Window Control had the option to display either application names or window titles. Perhaps that might be a good place to look for some sort of reference.

**Comment by kupiqu** [comment]
> There we go! I do believe the Active Window Control had the option to display either application names or window titles. Perhaps that might be a good place to look for some sort of reference.

Yes, I know. This applet is strongly based on AWC. Will try to see the best option available...
