### ISSUE TITLE
Display application titles for windows that do not display them.

### ISSUE THREAD

**Issue by Chromace** [kupiqu/plasma-active-application#5]
Continuing off of #4 , this is linked to the related problem of displaying application titles when they're not present at all in menu windows. For example, Pidgin only displays the name of the currently active chat, without showing its name at all. The expected result would be for the application to ignore the window title, and obtain the application name itself.

**Comment by kupiqu** [comment]
Thank you!

**Comment by kupiqu** [comment]
Fixed with commit 64d725045ce924542d6b2641512e2dd44645e94f
