### ISSUE TITLE
Prevent auto-capitalisation of application name replacements

### ISSUE THREAD

**Issue by Chromace** [kupiqu/plasma-active-application#9]
At the moment, name replacements are not entirely respected. If a person attempts to have a lowercase character at the beginning of a replacement, the widget will instead automatically capitalise the beginning. The expected result would be to have window replacements as-is, without modification.

An example of this can be seen here, where attempting to replace "QBittorrent" with "qBittorrent" results in no change.

![image](https://user-images.githubusercontent.com/16624211/48263720-37053a80-e47b-11e8-8230-4328f7b531d9.png)
![image](https://user-images.githubusercontent.com/16624211/48263743-42586600-e47b-11e8-8767-fe783b0abf25.png)

Naturally, capitalisation is usually a good thing to help make active application titles prettier, but some names (not many of them), do use lowercases at the start, so it'd be nice if the widget could respect that in the form of listening to the relevant replacements.

Many thanks for the previous work on getting application names to work!

**Comment by kupiqu** [comment]
Yeah, I see. I thought about it as a feature because some apps happen to suffer of the opposite, lower case for not reason. But I see your point. I'll see what I can do...

**Comment by Chromace** [comment]
Oh, there's certainly nothing wrong with how the application works at the moment! The default behaviour of it works just fine, especially considering that there's more programs that work better with their first letter capitalised. It's just little exceptions that don't work, I suppose, which is what the window replacement function is for, and as such, ought to function properly as, if that makes sense.

**Comment by kupiqu** [comment]
Fixed with commit c4f898fdf1c0c29fea8dcb4f25cdbf2691a59208

**Comment by kupiqu** [comment]
Automatic capitalization has been removed. One can always add capitalization in a replacement if needed.
